name: Artifact Practice
on: [push, workflow_dispatch]

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create a dummy report
        run: |
          echo "Server Health: Good" > report.txt
          echo "Disk Space: 80%" >> report.txt
          date >> report.txt

      - name: Upload the report
        uses: actions/upload-artifact@v4
        with:
          name: server-report          # The name you see on GitHub
          path: report.txt             # The file you want to save
