name: linux practise
on: [push]

jobs:
  my-first-job:
    runs-on: ubuntu-latest  # Move this 2 spaces to the right
    
    steps:                  # Move this 2 spaces to the right
      - name: list the files
        run: ls -lrt
        
      - name: show current directory
        run: pwd
        
      - name: check disk
        run: df -h
