name: Pipeline Data Share
on: [push]

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Secret-Code-123" > secret.txt
      - uses: actions/upload-artifact@v4
        with:
          name: security-token
          path: secret.txt

  use-data:
    runs-on: ubuntu-latest
    needs: generate-data           # Job 2 waits for Job 1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: security-token    # Downloads what Job 1 uploaded
      - name: Read the secret
        run: cat secret.txt
