name: Save System Logs
on: [push]

jobs:
  audit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Package List
        run: dpkg --get-selections > installed-software.txt

      - name: Save the file
        uses: actions/upload-artifact@v4
        with:
          name: system-audit-report
          path: installed-software.txt
