name: secret-practice
on: [push, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        env:
          MY_USER_NAME: \${{ secrets.MY_NAME }}
        run: |
          echo "The secret is loaded successfully."
          echo "Hello \$MY_USER_NAME"
